[project]
name = "dag-imoveis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru",
    "pandas",
    "openpyxl",  
    "Pillow",
    selenium webdriver-manager, 
    torch,  # Para ler arquivos Excel
]
